### ISSUE TITLE
"Confirm only" PIN mode not working on Arch Linux

### ISSUE THREAD

**Issue by dongcarl** [LedgerHQ/blue-app-openpgp-card#10]
First of all, I wanna say this is an amazing project. Once the deterministic seed feature is stable, I think this will change me life. I'm having one problem right now, which is that "Confirm only" PIN mode doesn't work for me. I know you mentioned in the docs that it may be that my client doesn't support it, but is there a way to make my client support it?

I have gpg 2.2.1 running on Arch Linux with the pcscd service running and the following `~/.gnupg/scdaemon.conf`:

```
reader-port "Ledger Token [Nano S] (0001) 01 00"
enable-pinpad-varlen
```

**Comment by cslashm** [comment]
Strange :), combo linux+gnupg should work.
Can you follow the doc/developper/quick-test.txt and tell me if it works or not

**Comment by dongcarl** [comment]
@cslashm Figured it out! Just had to `killall gpg-agent scdaemon` to load the conf correctly. Thanks!
