### ISSUE TITLE
Can't restore seed: "Key generation failed: File exists"

### ISSUE THREAD

**Issue by mhhf** [LedgerHQ/blue-app-openpgp-card#11]
Not sure if problem is with my local setup or with the ledger s but every time i reset the app and try to generate new keys following [this](https://github.com/LedgerHQ/blue-app-openpgp-card/blob/master/doc/user/blue-app-openpgp-card.pdf) instruction with seed: on i get the following error:
`Key generation failed: File exists`

However, after reapplying this the Signature key seems to chang (which should stay the same in seed mode if i understand it correctly?!) without affecting Encryption and Authentication keys.
Generating keys with seed: off works fine.

Tested it with empty `~/.gnupg/` directory and firmware reset on ledger s.

```
$ gpg --version
gpg (GnuPG/MacGPG2) 2.2.0
libgcrypt 1.8.1
```
On OS X 10.11.6

**Comment by mhhf** [comment]
nvm, [this solution solved it for me](https://github.com/LedgerHQ/blue-app-openpgp-card/issues/8#issuecomment-334121837)

**Comment by cslashm** [comment]
Happy to read you find the solution.
Doc is still not up-to-date, I'm sorry.

**Comment by mhhf** [comment]
Unfortunately the script doesn't seem to generate the actual keys, just overwrite the fingerprints.

Will rather wait for a more stable version/ docs.
Thanks for your work on this!

**Comment by dpc** [comment]
Couldn't the seeded generation happen on the device itself? Set name, email, comment, expiration date and get the key generated, all from the device's UI. After that the card would appear as already initialized.
