### ISSUE TITLE
pgp

### ISSUE THREAD

**Issue by eightsixeight** [LedgerHQ/blue-app-openpgp-card#20]
can these keys be used as a veracrypt device to unlock an encrypted drive ?

**Comment by drdaeman** [comment]
Don't think so. I don't think this app implements PIV to the extent of being able to store arbitrary data.

TrueCrypt/VeraCrypt actually treats tokens as glorified flash drives with PIN protection (or whatever), by putting a file on them, and then fetching it back. To the extent I've read into code of this app (which is just a little bit), it seems that it only does cryptographic operations and does not implement any form of protected storage for arbitrary data objects.

I could be wrong, though.

**Comment by cslashm** [comment]
No PIV yet, If you have any tool to test PIV card please contact me.
