### ISSUE TITLE
Signature counter doesn't work

### ISSUE THREAD

**Issue by JediWed** [LedgerHQ/blue-app-openpgp-card#3]
On every signing process the current signature counter is shown and it's always 0.
Doesn't matter how many times I have signed an email.

Tested on macOS Sierra 10.12.4
gpg (GnuPG/MacGPG2) 2.0.30
libgcrypt 1.6.6
4096R keys

**Comment by cslashm** [comment]
Thanks for report.
Bug confirmed. It will be fixed in RC7

**Comment by cslashm** [comment]
Fixed in RC7
