### ISSUE TITLE
Strange behavior generate key in seed mode

### ISSUE THREAD

**Issue by nyanloutre** [LedgerHQ/blue-app-openpgp-card#4]
When I generate a RSA key with seed mode enabled and all key on 4096 bits I get two key with 409**5** bits and one with 4096. I didn't get this behavior in normal mode.

**Comment by cslashm** [comment]
Hi,

That's normal (at least it's a choice).
Multiplying two numbers of n bits give you either 2n or 2n -1 bits.
As example, considers the 8 bits number 0x80:  0x80*0x80 = 0x4000 which is 15 bits length.

In OpenGPG card application when i generate the two prime p and q, I enforce p and q have n significant bits (2048 for 4096bits key), but I accept that modulus n=p*q   has only 2n-1 bits.

 Cédric

**Comment by nyanloutre** [comment]
Thanks for the information !

In fact this happened to me too when I was experimenting with RSA in python (to understand it)
